version: "3.8"
services:
    backend:
        build:
            context: ./backend
        # ports:
        #     - "5100:5000"
    frontend:
        build:
            context: ./my-app
        # ports:
        #     - "8080:3000"
    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/njserver.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
            - backend
