version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"