version: "2.8"
services:
    backend:
        build:
            context: ./backend
        ports:
            - "5100:5100"
    frontend:
        build:
            context: ./my-app
        ports:
            - "8080:3000"
