version: "3.8"
services:
    backend:
        build:
            context: ./backend
    frontend:
        build:
            context: ./my-app
    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/njserver.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
            - backend
