name: Docker Image CI

run-name: Build images for front, back and nginx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: |
           docker build -t frontend ./my-app/
           docker build -t nginx ./nginx/
           docker build ./backend/ -t backend
      working-directory: ./webpage
